---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```javascriptfunction doble(número){    return número * 2 ;  } ```"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```javascriptfunction doble(numero){    return numero + numero;   } ```"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```javascriptfunction doble(numero){    return numero * 2;   } ```"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "```javascriptfunction doble(numero)    return numero * 2;   ```"
  checked: false
name: No te entiendo nada
